import type { Metadata } from "next";
import "../globals.css";
import { DataProvider } from "@/components/app/state/DataProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body
        className="antialiased"
        style={{
          backgroundColor: "var(--color-surface-page)",
        }}
      >
        <DataProvider>{children}</DataProvider>
      </body>
    </html>
  );
}
