import type { Metadata } from "next";
import { Text_Me_One, Poppins } from "next/font/google";
import "./globals.css";

const TextMeOne = Text_Me_One({
  variable: "--font-text-me-one",
  weight: "400",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
 weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MetamorphIA",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: {children: React.ReactNode}) {
  return (
    <html
      lang="en"
      className={`${TextMeOne.variable} ${poppins.variable} h-full antialiased`}
    >
      <body className="font-(family-name:--font-poppins) min-h-full flex flex-col overflow-hidden">{children}</body>
    </html>
  );
}
